// import type { Metadata } from 'next'

// import './globals.css'

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode
// }>) {
//   return (
//     <html lang='en'>
//       <body className=''>{children}</body>
//     </html>
//   )
// }

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Islamic Education Series | Learn Islam',
  description:
    'An interactive platform for learning Islamic knowledge through audio lessons and PDF materials',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' dir='ltr'>
      <body
        className={`${inter.className} bg-gradient-to-b from-gray-50 to-blue-50 min-h-screen`}
      >
        <Header />
        <main className='container mx-auto px-4 py-8'>{children}</main>
        <footer className='bg-green-900 text-white py-6 text-center'>
          <div className='container mx-auto px-4'>
            <p className='text-lg'>
              © {new Date().getFullYear()} Islamic Education Series. All rights
              reserved.
            </p>
            <p className='text-gray-300 mt-2'>
              May Allah accept our efforts and grant us beneficial knowledge
            </p>
          </div>
        </footer>
      </body>
    </html>
  )
}
